name: Build unsigned dylib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build dylib for device (arm64)
        run: |
              xcrun -sdk iphoneos clang -dynamiclib getpid-tweak.m -arch arm64 -fobjc-arc -o getpid-tweak.dylib

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dylibs
          path: getpid-tweak.dylib
          retention-days: 90
